# Generated by Django 5.2.6 on 2025-09-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='news',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
